global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "submission-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["submission:8081"]

  - job_name: "catalog-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["catalog:8082"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
