gateway:
  name: paper-demo-gateway
  namespace: ""
  selector:
    istio: ingressgateway
  port: 80
  protocol: HTTP
  hosts:
    - "*"

virtualService:
  name: paper-demo-vs
  namespace: ""
  hosts:
    - "*"
  routes:
    - match:
        uri:
          prefix: /api/v1/submissions
      destination:
        host: dev-submission
        port: 8081
    - match:
        uri:
          prefix: /api/internal
      destination:
        host: dev-submission
        port: 8081
    - match:
        uri:
          prefix: /api/v1/catalog
      destination:
        host: dev-catalog
        port: 8082
    - match:
        uri:
          prefix: /
      destination:
        host: dev-frontend
        port: 8080
